### ISSUE TITLE
What URL should I put in CIAN_URLS?

### ISSUE THREAD

**Issue by mixartemev** [yarysh/cian_bot#2]
I tried 'https://www.cian.ru/kupit-kvartiru-1-komn-ili-2-komn/' for example it's not working.
Xlsx file is empty. 
`xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'<!DOCTYP'`

**Comment by yarysh** [comment]
For this url you should use 
https://www.cian.ru/export/xls/offers/?deal_type=sale&engine_version=2&offer_type=flat&region=1&room1=1&room2=1

You can get this url from the "Сохранить файл в Excel" button.
